// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkvFfY1jdkAXmGC7d6mWoWxluUo15GPwk',
    appId: '1:201141453204:web:7b246c77e029a549680f81',
    messagingSenderId: '201141453204',
    projectId: 'campus-nefu-c44e4',
    authDomain: 'campus-nefu-c44e4.firebaseapp.com',
    storageBucket: 'campus-nefu-c44e4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByNfpJUgFrF5OklRWyeFqTEqLpF0RQOPw',
    appId: '1:201141453204:android:e080d7ba06ef9a7b680f81',
    messagingSenderId: '201141453204',
    projectId: 'campus-nefu-c44e4',
    storageBucket: 'campus-nefu-c44e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6CuwO0gG4psW-mr8kfiGBnFjJJq6_gc8',
    appId: '1:201141453204:ios:1ebe39b9df4a6fff680f81',
    messagingSenderId: '201141453204',
    projectId: 'campus-nefu-c44e4',
    storageBucket: 'campus-nefu-c44e4.firebasestorage.app',
    iosBundleId: 'com.example.campusImi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6CuwO0gG4psW-mr8kfiGBnFjJJq6_gc8',
    appId: '1:201141453204:ios:1ebe39b9df4a6fff680f81',
    messagingSenderId: '201141453204',
    projectId: 'campus-nefu-c44e4',
    storageBucket: 'campus-nefu-c44e4.firebasestorage.app',
    iosBundleId: 'com.example.campusImi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkvFfY1jdkAXmGC7d6mWoWxluUo15GPwk',
    appId: '1:201141453204:web:6590e9b62f98042b680f81',
    messagingSenderId: '201141453204',
    projectId: 'campus-nefu-c44e4',
    authDomain: 'campus-nefu-c44e4.firebaseapp.com',
    storageBucket: 'campus-nefu-c44e4.firebasestorage.app',
  );
}
